export const ADMINPATHS = {
  APPPATH: '/app',
  CALLBACK: "*",
  DEFAULT: "/admin",
  LISTING: "/admin/listing/",
  LISTINGREQUESTS: "/admin/listing/listing-requests",
  LISTINGREQUESTSDETAIL: "/admin/listing/listing-requests/detail",
  LISTINGDETAIL: '/admin/listing/detail',
  DASHBOARD: "/admin/dashboard/",
  SETTINGS: "/admin/dashboard/setting",
  USERMANAGEMENT: "/admin/user-management",
  USERDETAIL: '/admin/user-management/detail',
  BOOKINGS: "/admin/booking",
  BOOKINGSDETAIL: '/admin/booking/detail',
  BUSINESSADMINS: '/admin/business-admin',
  BACKGROUNDCHECK: '/admin/backgroun-check',
  BACKGROUNDCHECKDETAIL: '/admin/backgroun-check/detail',
  EVICTIONREQUESTS: '/admin/eviction-request',
  EVICTIONREQUESTSDERAIL: '/admin/eviction-request/detail',
  NOTIFICATION: '/admin/notification',
  MESSAGES: '/admin/messages',
  MESSAGESDETAIL: '/admin/messages/detail',
  MANAGEDOCUMENT: '/admin/manage-document',
};
